FROM node:20.12.0-alpine3.19

RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY package.json turbo.json pnpm-lock.yaml pnpm-workspace.yaml  ./

COPY apps ./apps
COPY packages ./packages

#install dependedcies
RUN pnpm install

RUN pnpm run db:generate

RUN pnpm run build

CMD ["pnpm","run","start-web"]