FROM node:22.12.0-alpine3.19

RUN npm install -g pnpm

WORKDIR /usr/src/app
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

COPY package.json turbo.json pnpm-lock.yaml pnpm-workspace.yaml  ./

COPY apps ./apps
COPY packages ./packages


RUN echo "DATABASE_URL=${DATABASE_URL}" > packages/db-config/.env

#install dependedcies
RUN pnpm install

RUN pnpm run db:migrate

RUN pnpm run db:generate

RUN pnpm run build

CMD ["pnpm","run","start-backend"]